### PR TITLE
Bump html table

### PR DESCRIPTION
**Pull request by cvagner**
I share this contribution in case anyone is interested.

### CODE REVIEW

**Comment by cvagner** [comment]
@adriens or @mbarre  your project is interesting to me. Are you using it ? Can you review please ?

**Comment by adriens** [comment]
Hey @cvagner , thanks a lot for the PR and the kind feedback.

Would you slightly modify the docker section so the script works out of the box :pray: :grey_question: 

By default, I got this:

<pre><font color="#5FD700">❯</font> docker run --rm \
  -v ~/.docker/config.json:/config/config.json:ro -e &quot;DOCKER_CONFIG=/config&quot; \
  -v ${PWD}/tmpl/html-table.tmpl:/config/html-table.tmpl:ro \
  anchore/grype:latest \
  \
  $IMAGE -o template -t /config/html-table.tmpl &gt; work/analysis.html
WARNING: Error loading config file: /home/adriens/.docker/config.json: read /home/adriens/.docker/config.json: is a directory
2 errors occurred:
	* failed to load vulnerability db: vulnerability database is invalid (run db update to correct): database metadata not found: /.cache/grype/db/5
	* failed to catalog: unable to load image: could not read image: Get &quot;https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/a8/a8758716bb6aa4d90071160d27028fe4eaee7ce8166221a97d30440c8eac2be6/data?verify=REDACTED&quot;: dial tcp [2606:4700::6810:68cf]:443: connect: cannot assign requested address</pre>

**Comment by cvagner** [comment]
Hi @adriens,

You are right, it's better to procede like you suggested (no config by default with a public image).
I updated my commit so that it works out of the box.

I think you will have to remove the directory created by the initial command with sudo `~/.docker/config.json` because docker creates a directory in case of a bind mount file or directory is missing on host.

**Comment by cvagner** [comment]
So @adriens, did you reviewed ? :smile:

**Comment by adriens** [comment]
Hi @cvagner , sorry for very late answer. Nopt, I did not, but I will :+1:

**Comment by adriens** [comment]
:ok_hand:  from scratch on Killercoda : 

image

**Comment by adriens** [comment]
Thank you @cvagner for the contribution :pray:

**Comment by cvagner** [comment]
You're welcome.

**Pull request merged**
